# config
vit_name: "tiny" # tiny, small, b+
model_type: "sam_2"
sam_ckpt: "checkpoints/sam2_hiera_t.pt"
# ft_ckpt: "checkpoints/best_model_sam2_fold0.pth"
ft_ckpt: null
rank: -1 # -1 means don't use


deterministic: true
seed: 1234

verbose: false
conf_threshold: 0.5
use_prev_mask: false
visualize: false

# debugging/viz intervals
save_img: false # false for now?

# data
img_size: 384
seg_size: 224 # this represents segmentation dimensions
num_classes: 3
oversample: 0
num_slices: 143
modalities: ["t2w", "t2w", "t2w"]
# modalities: ["t2f", "t2w", "t1c", "t1n"]

# modalities_yolo: ["flair", "t1ce", "t2"]https://dl.fbaipublicfiles.com/segment_anything_2/072824/

# detection
modalities_yolo: []
use_box: false

use_cache: false
pseudo_slices_prop: 0

# processor
n_gpu: 1
num_workers: 0

# training loop
batch_size_train: 4
batch_size_val: 4

warmup_epochs: 2
use_warmup: false

max_epochs: 20
base_lr: 0.000015 # 0.000015
val_every: 1
fold_train: "-1" # [0,1,3,4]
fold_val: [0] # just testing 3
fold_num: 10

optimizer: "ADAMW" # ADAMW or SGD
loss: "GDF" # Loss configuration (GDF, DL, DCE)
use_mse: false
scheduler: "COSAN" # Scheduler (EXP, COSAN, COSANWARM, NONE)

use_amp: true
compile: false
use_curriculum: false

preprocessing:
  useNorm: true
  resize: true
  resize_dims: [384,384]

augmentation:
  flipH: 
    p: 0.3
  flipW:
    p: 0.3
  flipD:
    p: 0.3
  FG:
    p: 0.5
    offsets: 0.15
  zoom:
    p: 0.2
    min: 0.9
    max: 1.1